%---------------------------------------------
% 
% GUI Program
% 
% by K.Kamura  07/06/2019
% 
%---------------------------------------------
clear
close all force

v = get(0, 'MonitorPosition');

WIDTH = 750;
HEIGHT = 300;
X_MIN = v(3) - WIDTH * 2.5;
Y_MIN = v(4) - HEIGHT * 3;

Figure_position = [X_MIN Y_MIN WIDTH HEIGHT];
color = [0.6 0.7 1];
waveform = 1;
itdild_select = 1;

global pos
global order

pos = [-1 -3/4 -1/2 -1/4 0 1/4 1/2 3/4 1];
order = [1 9 5 3 7 2 4 6 8];

%% figureの作成
H0 = uifigure('Position', Figure_position,...
    'NumberTitle','off',...
    'Name','ITD & ILD',...
    'MenuBar', 'none',...
    'Color', color,...
    'Units', 'pixels',...
    'Visible', 'on');

%% menu
menu_2 = uimenu(H0,...
    'Text', 'Waveform');
    uimenu(menu_2,...
        'Text', 'Whitenoise',...
        'MenuSelectedFcn', 'waveform = 1;');
    uimenu(menu_2,...
        'Text', 'Sine Wave',...
        'MenuSelectedFcn', 'waveform = 2;');
menu_3 = uimenu(H0,...
    'Text', 'ITD/ILD');
    uimenu(menu_3,...
        'Text', 'ILD',...
        'MenuSelectedFcn', 'itdild_select = 1;');
    uimenu(menu_3,...
        'Text', 'ITD',...
        'MenuSelectedFcn', 'itdild_select = 2;');

%% ラベル
label1 = uilabel(H0,...
    'Position', [WIDTH/2-10 HEIGHT-90 500 100],...
    'Text', 'ILD',...
    'FontSize', 20);
label2 = uilabel(H0,...
    'Position', [WIDTH/2-10 HEIGHT-185 500 100],...
    'Text', 'ITD',...
    'FontSize', 20);
label3 = uilabel(H0,...
    'Position', [WIDTH-35 HEIGHT-141 100 100],...
    'Text', '[dB]');
label4 = uilabel(H0,...
    'Position', [WIDTH-30 HEIGHT-240 100 100],...
    'Text', '[μs]');
label5 = uilabel(H0,...
    'Position', [WIDTH/2+50 HEIGHT-90 500 100],...
    'Text', '0 [dB]',...
    'fontsize', 20);
label6 = uilabel(H0,...
    'Position', [WIDTH/2+50 HEIGHT-185 500 100],...
    'Text', '0 [μs]',...
    'fontsize', 20);

%% Stop & Keep Button
button_stop = uibutton(H0, 'state',...
    'Position', [WIDTH-500 HEIGHT-60 80 30],...
    'Text', 'Stop');

button_keep = uibutton(H0, 'state',...
    'Position', [WIDTH-180 HEIGHT-60 80 30],...
    'BackgroundColor', [0.5 1 0.5],...
    'Text', 'Both');

%% スライダ
sld_ild = uislider(H0,...
    'Position', [WIDTH/2-320 HEIGHT-80 640 3],...
    'Limits', [-40 40]);

sld_itd = uislider(H0,...
    'Position', [WIDTH/2-320 HEIGHT-170 650 3],...
    'Limits', [-1700 1700],...
    'ValueChangingFcn',@(sld_itd, event) updatesld_ild(button_keep, sld_itd, sld_ild, event));

sld_ild.ValueChangingFcn = @(sld_ild,event) updatesld_itd(button_keep, sld_itd, sld_ild, event);

%% Reset Button
color_bt = [0.5 1 1];
button_ild = uibutton(H0,...
    'Position', [WIDTH-90 HEIGHT-60 80 30],...
    'Text', 'Clear ILD',...
    'BackgroundColor', color_bt,...
    'ButtonPushedFcn',@(button_ild, event) reset_value(sld_ild));

button_itd = uibutton(H0,...
    'Position', [WIDTH-90 HEIGHT-150 80 30],...
    'Text', 'Clear ITD',...
    'BackgroundColor', color_bt,...
    'ButtonPushedFcn',@(button_itd, event) reset_value(sld_itd));

global i
i = 1;
global ild
global itd
ild = [0 0 0 0 0 0 0 0 0];
itd = [0 0 0 0 0 0 0 0 0];

label = uilabel(H0,...
    'Position', [WIDTH-500 HEIGHT-280 80 30],...
    'Text', '-1',...
    'FontSize', 20);

button_de = uibutton(H0,...
    'Position', [WIDTH-90 HEIGHT-280 80 30],...
    'Text', '決定',...
    'ButtonPushedFcn',@(button_de, event) decision(evalin('base', 'itdild_select'), label, sld_ild, sld_itd));

button_pl = uibutton(H0,...
    'Position', [WIDTH-200 HEIGHT-280 80 30],...
    'Text', '再生',...
    'ButtonPushedFcn',@(button_pl, event) play(evalin('base', 'itdild_select'), sld_ild, sld_itd));


%% Play Button
button_play = uibutton(H0,...
    'Position', [WIDTH-590 HEIGHT-60 80 30],...
    'Text', 'Play',...
    'ButtonPushedFcn',@(button_play, event) itdild2(sld_ild, sld_itd, label5, label6, button_stop, evalin('base', 'waveform')));
%% Answer Figure
XMIN = v(3) * 0.49;
YMIN = v(4) * 0.1;
WIDTH = v(3) * 0.5;
HEIGHT = WIDTH * 4 / 5;
figpos = [XMIN YMIN WIDTH HEIGHT];

%% Bothボタンが押されたとき、itdのスライダも同時に動かす関数
function updatesld_itd(keep, sld_itd, sld_ild, event)
if keep.Value == 1
    sld_itd.Value = event.Value * 50;
    sld_ild.Value = event.Value;
else
    sld_ild.Value = event.Value;
end
end

%% Bothボタンが押されたとき、ildのスライダも同時に動かす関数
function updatesld_ild(keep, sld_itd, sld_ild, event)
if keep.Value == 1
    sld_ild.Value = event.Value * 0.02;
    sld_itd.Value = event.Value;
else
    sld_itd.Value = event.Value;
end
end

%% スライダの値を0にリセットする関数
function reset_value(obj)
obj.Value = 0;
end