clear
close all force

v = get(0, 'MonitorPosition');
XMIN = v(3) * 0.1;
YMIN = v(4) * 0.1;
WIDTH = v(3) * 0.6;
HEIGHT = WIDTH * 4/5;
pos = [XMIN YMIN WIDTH HEIGHT];

H0 = figure('Pos', pos,...
    'Color', [0 0 0],...
    'NumberTitle',  'off',...
    'Name', 'Sound Localization',...
    'MenuBar', 'none');

A = imread('image.jpeg');
image(A);
set(gca, 'Visible', 'off');
hold on
h = images.roi.Circle(gca, 'Center', [448 380], 'Radius', 50, 'FaceAlpha', 1);

B_start = uicontrol(H0,...
    'Style', 'pushbutton',...
    'String', 'Start',...
    'FontName', 'Arial',...
    'FontSize', 16,...
    'Position', [XMIN*0.3 YMIN*0.2 WIDTH*0.08 HEIGHT*0.04],...
    'Callback', 'pos = start(h);');